#!/bin/bash

main() {
    case $1 in
      reset) reset ;;
      zipit) zipit ;;
      *) help ;;
    esac
}

reset(){
    while read LINE; do
        DEP=$(echo $LINE | cut -d'=' -f1)
        DEP=$(echo $DEP | cut -d'<' -f1)
        DEP=$(echo $DEP | cut -d'>' -f1)
        rm -rf ${DEP}
    done < requirements.txt
    rm *.zip
}

zipit(){
    echo "Creating temperory virtual environment..."
    python3 -m venv venv
    source venv/bin/activate
    pip install --upgrade pip > /dev/null
    echo "Installing dependencies..."
    pip install -r requirements.txt > /dev/null

    while read LINE; do
        DEP=$(echo $LINE | cut -d'=' -f1)
        DEP=$(echo $DEP | cut -d'<' -f1)
        DEP=$(echo $DEP | cut -d'>' -f1)
        cp -r venv/lib/python3.8/site-packages/${DEP} .
    done < requirements.txt
    rm -rf venv
    ZIP_FILENAME=${PWD##*/}.zip
    echo "Creating zip '${ZIP_FILENAME}'..."
    zip -r ${ZIP_FILENAME} * --exclude run requirements.txt
    echo
    echo "Created zip file..."
    du -h ${ZIP_FILENAME}
}

help() {
    echo "Please refer main function in the run script for valid options"
}

main $*
