#!/bin/bash

main() {
    case $1 in
      install) install ;;
      reset) reset ;;
      zip) install && zipit ;;
      *) help ;;
    esac
}

install(){
    python3 -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt

    while read LINE; do
        DEP=$(echo $LINE | cut -d'=' -f1)
        DEP=$(echo $DEP | cut -d'<' -f1)
        DEP=$(echo $DEP | cut -d'>' -f1)
        cp -r venv/lib/python3.8/site-packages/${DEP} .
    done < requirements.txt
    rm -rf venv
}

reset(){
    while read LINE; do
        DEP=$(echo $LINE | cut -d'=' -f1)
        DEP=$(echo $DEP | cut -d'<' -f1)
        DEP=$(echo $DEP | cut -d'>' -f1)
        rm -rf ${DEP}
    done < requirements.txt
    rm *.zip
}

zipit(){
    zip -r ${PWD##*/}.zip * --exclude run requirements.txt
}

help() {
    echo "Please refer main function in the run script for valid options"
}

main $*
